name: limmonde
description: A news application for the journal "L'immonde".

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' 

# The version number of your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core dependency
  firebase_core:  ^3.3.0
  # Cloud Firestore for storing and retrieving articles
  cloud_firestore: ^5.2.1

  # For image network handling and other features
  cached_network_image:  ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:
  #  - assets/images/

